language: python
cache: pip
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: yes
    - python: nightly
      dist: xenial
      sudo: yes
    - python: pypy
    - python: pypy3

script:
  - python setup.py test
